"""new column contact

Revision ID: 00b3d7b58b90
Revises: aeb933fb9d4c
Create Date: 2024-04-18 22:32:09.487418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00b3d7b58b90'
down_revision: Union[str, None] = 'aeb933fb9d4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('contact_email', sa.String(), nullable=True))
    op.add_column('persons', sa.Column('contact_SNL', sa.String(), nullable=True))
    op.add_column('persons', sa.Column('contact_telegram', sa.String(), nullable=True))
    op.drop_column('persons', 'contacts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('contacts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('persons', 'contact_telegram')
    op.drop_column('persons', 'contact_SNL')
    op.drop_column('persons', 'contact_email')
    # ### end Alembic commands ###
