"""новая колонка в admins

Revision ID: 5308f3268bb8
Revises: 00b3d7b58b90
Create Date: 2024-04-21 11:01:19.883258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5308f3268bb8'
down_revision: Union[str, None] = '00b3d7b58b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'token')
    # ### end Alembic commands ###
