"""empty message

Revision ID: 86c95fe266eb
Revises: 58684a1594d8
Create Date: 2024-04-24 11:25:48.121211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c95fe266eb'
down_revision: Union[str, None] = '58684a1594d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('check', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'check')
    # ### end Alembic commands ###
