"""empty message

Revision ID: c4454b888caa
Revises: 5308f3268bb8
Create Date: 2024-04-21 11:20:08.648663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4454b888caa'
down_revision: Union[str, None] = '5308f3268bb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('token', sa.String(), nullable=True)
    )
    op.drop_column('admins', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('token')
    # ### end Alembic commands ###
