"""empty message

Revision ID: 9f16237019b5
Revises: fb6a518e24d4
Create Date: 2024-04-14 16:44:03.335008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f16237019b5'
down_revision: Union[str, None] = 'fb6a518e24d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('date_birth', sa.Integer(), nullable=True))
    op.drop_column('persons', 'data_birth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('data_birth', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('persons', 'date_birth')
    # ### end Alembic commands ###
